#!/usr/bin/env python3
"""One-time deterministic extraction of the MM function registry.

Source: 02_MM_Function_Registry.md (sibling doc). Every function entry is a
single fenced ```yaml block under a '## <n> MM_FUNCTION' heading, already in
a directly-parseable shape (function/category/syntax/parameters/...). This
script concatenates those blocks into references/mm-function-registry.yaml,
which becomes the authoritative "Mind-supported function list" that
FRM-002 Unsupported Functions checks against.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

import yaml

BLOCK_RE = re.compile(r"```yaml\n(.*?)\n```", re.S)

# A handful of list items in the source doc quote a leading token but then
# continue with unquoted trailing text on the same line (e.g. `- "SIM" is
# used for ...`), which is not valid YAML (a quoted scalar can't have
# trailing plain content). Drop the inner quotes on those lines only; the
# quoted word's meaning is unaffected.
INLINE_QUOTE_FIX_RE = re.compile(r'^(\s*-\s*)"([^"]+)"(\s+\S.*)$', re.M)


def extract_functions(text: str) -> list[dict]:
    functions = []
    for m in BLOCK_RE.finditer(text):
        block = INLINE_QUOTE_FIX_RE.sub(r"\1\2\3", m.group(1))
        try:
            data = yaml.safe_load(block)
        except yaml.YAMLError as exc:
            print(f"  WARNING: could not parse a yaml block ({exc})")
            continue
        # Section 1.3 documents the entry format as a template block with
        # every field empty (function: <blank>) -- skip it, not a real entry.
        if isinstance(data, dict) and data.get("function"):
            functions.append(data)
    return functions


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", default=str(Path(__file__).resolve().parents[2] / "02_MM_Function_Registry.md"))
    ap.add_argument("--output", default=str(Path(__file__).resolve().parents[1] / "references" / "mm-function-registry.yaml"))
    args = ap.parse_args()

    src_path = Path(args.source)
    out_path = Path(args.output)
    text = src_path.read_text(encoding="utf-8")
    functions = extract_functions(text)
    print(f"Parsed {len(functions)} function entries from {src_path.name}")

    names = [f["function"] for f in functions]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        print(f"  WARNING: duplicate function names: {sorted(dupes)}")

    doc = {
        "version": "1.0.0",
        "source_document": src_path.name,
        "note": "Generated by tools/mine_function_registry.py. Do not hand-edit; re-run the script against an updated source doc instead.",
        "functions": functions,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml.dump(doc, sort_keys=False, allow_unicode=True, width=100), encoding="utf-8")
    print(f"  wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
